name: ons_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  http: ^1.2.2
  dio: ^5.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  pdfx: ^2.6.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  jwt_decoder: ^2.0.1
  geolocator: ^13.0.1 # Removed the extra "dependencies:" line here
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated to 5.0.0 for better Dart 3 compatibility

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/hero.jpg